### ISSUE TITLE
Use Drupal migration for data migrations instead of custom creating entities 

### ISSUE THREAD

**Issue by JayKandari** [gunjana/migrationtodrupal#1]
With the current code, 
I can see the data migration is started on `MappingForm::processForm()` method and eventually it reads the JSON file present in the module. And with help of `ProcessDataBatch::processData()` method we are importing those contents 1 by 1. 

Instead of this, can we do data migration with Migrate API (Ref: https://api.drupal.org/api/drupal/core%21modules%21migrate%21migrate.api.php/group/migration/10)

**Comment by gunjana** [comment]
Removed processData & used migration api to migrate data instead

**Comment by JayKandari** [comment]
Reviewed the migration and it looks good. Thus closing the ticket.
