### ISSUE TITLE
Mapping config form should only do mappings

### ISSUE THREAD

**Issue by JayKandari** [gunjana/migrationtodrupal#3]
Currently the mapping config is stored in `migration_to_drupal.mapping` config. Exclude any processing on form save. 

This form should be just to save the config mappings.. These mappings will be read and then used by the migrations dynamically and do migrations.

**Comment by gunjana** [comment]
Removed processing button from mapping form

**Comment by JayKandari** [comment]
Changes for this issue seems fixed. Closing the ticket.
